#Makefile fo the Stack test Main
all: ../Containers/GenericContainers/List/List.h ../Containers/GenericContainers/Stack/Stack.h ../Containers/GenericContainers/Queue/Queue.h Main.cpp
	g++ -o stack Main.cpp
clean:
	rm stack
